### ISSUE TITLE
Write Tests for AuthService

### ISSUE THREAD

**Issue by MarkHmnv** [UpTalent/AuthService#22]
### Description
Write Tests for AuthService

### Tasks

- [x] Registrate new User successfully
- [x] Registrate new User with earlier occupied email
- [x] Registrate new User and forget input some data
- [x] Verify User account successfully
- [x] Verify User account with non-found token
- [x] Log in successfully
- [x] Log in with max reached attempts
- [x] Log in when already authorized
- [x] Log in when account is blocked
- [x] Log in when account is not verified
- [x] Logout successfully
