### ISSUE TITLE
Redis Caching for Unverified Users

### ISSUE THREAD

**Issue by MarkHmnv** [UpTalent/AuthService#7]
### Description
Before a user can successfully register, they need to verify their email address using the NotificationService. Unverified user accounts will be stored in Redis cache, and if a user remains unverified for more than 1 hour, their account will be automatically removed from the cache.

### Tasks
- [x] Configure Redis
- [x] Implement a mechanism to store unverified user accounts in Redis cache
- [x] Set an expiration time of 1 hour for unverified user accounts in Redis
- [x] Implement the logic to handle email verification callbacks from the NotificationService
